name: StrawWeb CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Git clone and deploy to docker
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /tmp; git clone git@github.com:StrawberryCorps/strawberrycorps.github.io.git; cd strawberrycorps.github.io; docker build . -t strawberrycorps-web; docker stop strawberrycorps-web; docker rm strawberrycorps-web; docker run -d -p 8080:80 strawberrycorps-web --name strawberrycorps-web; cd ..; rm -rf /tmp/strawberrycorps.github.io.git"
